language: shell

os: linux
dist: bionic

services:
  - docker

cache:
  bundler: true
  directories:
    - $HOME/docker

before_cache:
  # Save tagged docker images
  - ls $HOME/docker
  - >
    mkdir -p $HOME/docker
  - echo "$(ls $HOME/docker)"
  - ls $HOME/docker"

before_install:
  # Load cached docker images
  - echo "$(ls $HOME/docker)"
  #- >
  #  if [[ -d $HOME/docker ]] && [[ ! -z "$(ls $HOME/docker)" ]]; then docker load -i $HOME/docker/*.tar.gz; fi
  #- echo "$(docker images -a)"
  #

before_script:
  - echo "kopet here"

install:
  - >
    docker build --cache-from=debian:buster -t builder .
jobs:
  include:
    - stage: build
      script:
        - >
          bash ./build.sh
stages:
  - build
