language: shell

os: linux
dist: bionic

services:
  - docker

cache:
  bundler: true
  directories:
    - $HOME/docker

before_cache:
  # Save tagged docker images
  - echo "$(docker images -a)"
  - >
    mkdir -p $HOME/docker && if [[ ! -f "$HOME/docker/$(docker images --format '{{.Repository}} {{.ID}}' | grep builder | xargs -n 2 | cut -d' ' -f2).tar.gz" ]]; then echo 'docker save builder:latest fedora:latest | gzip -2 > $HOME/docker/$1.tar.gz' | bash /dev/stdin $(docker images --format '{{.Repository}} {{.ID}}' | grep builder | xargs -n 2 | cut -d' ' -f2); fi
  - echo "$(ls $HOME/docker)"

before_install:
  # Load cached docker images
  - echo "$(ls $HOME/docker)"
  - >
    if [[ -d $HOME/docker ]] && [[ ! -z "$(ls $HOME/docker)" ]]; then docker load -i $HOME/docker/*.tar.gz; fi
  - echo "$(docker images -a)"

before_script:
  - echo "kopet here"

install:
  - >
    docker build --cache-from=builder:latest,debian:buster -t builder .
jobs:
  include:
    - stage: build
      script:
        - >
          bash ./build.sh
stages:
  - build
